// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// DrugAllergy is the predicate function for drugallergy builders.
type DrugAllergy func(*sql.Selector)

// Manner is the predicate function for manner builders.
type Manner func(*sql.Selector)

// Medicine is the predicate function for medicine builders.
type Medicine func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)
