// Code generated by entc, DO NOT EDIT.

package drugallergy

const (
	// Label holds the string label denoting the drugallergy type in the database.
	Label = "drug_allergy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeDoctor holds the string denoting the doctor edge name in mutations.
	EdgeDoctor = "doctor"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeMedicine holds the string denoting the medicine edge name in mutations.
	EdgeMedicine = "medicine"
	// EdgeManner holds the string denoting the manner edge name in mutations.
	EdgeManner = "manner"

	// Table holds the table name of the drugallergy in the database.
	Table = "drug_allergies"
	// DoctorTable is the table the holds the doctor relation/edge.
	DoctorTable = "drug_allergies"
	// DoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	DoctorInverseTable = "doctors"
	// DoctorColumn is the table column denoting the doctor relation/edge.
	DoctorColumn = "doctor_id"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "drug_allergies"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
	// MedicineTable is the table the holds the medicine relation/edge.
	MedicineTable = "drug_allergies"
	// MedicineInverseTable is the table name for the Medicine entity.
	// It exists in this package in order to avoid circular dependency with the "medicine" package.
	MedicineInverseTable = "medicines"
	// MedicineColumn is the table column denoting the medicine relation/edge.
	MedicineColumn = "medicine_id"
	// MannerTable is the table the holds the manner relation/edge.
	MannerTable = "drug_allergies"
	// MannerInverseTable is the table name for the Manner entity.
	// It exists in this package in order to avoid circular dependency with the "manner" package.
	MannerInverseTable = "manners"
	// MannerColumn is the table column denoting the manner relation/edge.
	MannerColumn = "manner_id"
)

// Columns holds all SQL columns for drugallergy fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the DrugAllergy type.
var ForeignKeys = []string{
	"doctor_id",
	"manner_id",
	"medicine_id",
	"patient_id",
}
