// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"

	// EdgePatientDrugAllergy holds the string denoting the patient_drugallergy edge name in mutations.
	EdgePatientDrugAllergy = "Patient_DrugAllergy"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// PatientDrugAllergyTable is the table the holds the Patient_DrugAllergy relation/edge.
	PatientDrugAllergyTable = "drug_allergies"
	// PatientDrugAllergyInverseTable is the table name for the DrugAllergy entity.
	// It exists in this package in order to avoid circular dependency with the "drugallergy" package.
	PatientDrugAllergyInverseTable = "drug_allergies"
	// PatientDrugAllergyColumn is the table column denoting the Patient_DrugAllergy relation/edge.
	PatientDrugAllergyColumn = "patient_id"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
}

var (
	// PatientNameValidator is a validator for the "Patient_Name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
)
