// Code generated by entc, DO NOT EDIT.

package medicine

const (
	// Label holds the string label denoting the medicine type in the database.
	Label = "medicine"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMedicineName holds the string denoting the medicine_name field in the database.
	FieldMedicineName = "medicine_name"

	// EdgeMedicineDrugAllergy holds the string denoting the medicine_drugallergy edge name in mutations.
	EdgeMedicineDrugAllergy = "Medicine_DrugAllergy"

	// Table holds the table name of the medicine in the database.
	Table = "medicines"
	// MedicineDrugAllergyTable is the table the holds the Medicine_DrugAllergy relation/edge.
	MedicineDrugAllergyTable = "drug_allergies"
	// MedicineDrugAllergyInverseTable is the table name for the DrugAllergy entity.
	// It exists in this package in order to avoid circular dependency with the "drugallergy" package.
	MedicineDrugAllergyInverseTable = "drug_allergies"
	// MedicineDrugAllergyColumn is the table column denoting the Medicine_DrugAllergy relation/edge.
	MedicineDrugAllergyColumn = "medicine_id"
)

// Columns holds all SQL columns for medicine fields.
var Columns = []string{
	FieldID,
	FieldMedicineName,
}

var (
	// MedicineNameValidator is a validator for the "Medicine_Name" field. It is called by the builders before save.
	MedicineNameValidator func(string) error
)
