// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/mmildd_s/app/ent/doctor"
	"github.com/mmildd_s/app/ent/drugallergy"
	"github.com/mmildd_s/app/ent/manner"
	"github.com/mmildd_s/app/ent/medicine"
	"github.com/mmildd_s/app/ent/patient"
)

// DrugAllergyCreate is the builder for creating a DrugAllergy entity.
type DrugAllergyCreate struct {
	config
	mutation *DrugAllergyMutation
	hooks    []Hook
}

// SetDoctorID sets the doctor edge to Doctor by id.
func (dac *DrugAllergyCreate) SetDoctorID(id int) *DrugAllergyCreate {
	dac.mutation.SetDoctorID(id)
	return dac
}

// SetNillableDoctorID sets the doctor edge to Doctor by id if the given value is not nil.
func (dac *DrugAllergyCreate) SetNillableDoctorID(id *int) *DrugAllergyCreate {
	if id != nil {
		dac = dac.SetDoctorID(*id)
	}
	return dac
}

// SetDoctor sets the doctor edge to Doctor.
func (dac *DrugAllergyCreate) SetDoctor(d *Doctor) *DrugAllergyCreate {
	return dac.SetDoctorID(d.ID)
}

// SetPatientID sets the patient edge to Patient by id.
func (dac *DrugAllergyCreate) SetPatientID(id int) *DrugAllergyCreate {
	dac.mutation.SetPatientID(id)
	return dac
}

// SetNillablePatientID sets the patient edge to Patient by id if the given value is not nil.
func (dac *DrugAllergyCreate) SetNillablePatientID(id *int) *DrugAllergyCreate {
	if id != nil {
		dac = dac.SetPatientID(*id)
	}
	return dac
}

// SetPatient sets the patient edge to Patient.
func (dac *DrugAllergyCreate) SetPatient(p *Patient) *DrugAllergyCreate {
	return dac.SetPatientID(p.ID)
}

// SetMedicineID sets the medicine edge to Medicine by id.
func (dac *DrugAllergyCreate) SetMedicineID(id int) *DrugAllergyCreate {
	dac.mutation.SetMedicineID(id)
	return dac
}

// SetNillableMedicineID sets the medicine edge to Medicine by id if the given value is not nil.
func (dac *DrugAllergyCreate) SetNillableMedicineID(id *int) *DrugAllergyCreate {
	if id != nil {
		dac = dac.SetMedicineID(*id)
	}
	return dac
}

// SetMedicine sets the medicine edge to Medicine.
func (dac *DrugAllergyCreate) SetMedicine(m *Medicine) *DrugAllergyCreate {
	return dac.SetMedicineID(m.ID)
}

// SetMannerID sets the manner edge to Manner by id.
func (dac *DrugAllergyCreate) SetMannerID(id int) *DrugAllergyCreate {
	dac.mutation.SetMannerID(id)
	return dac
}

// SetNillableMannerID sets the manner edge to Manner by id if the given value is not nil.
func (dac *DrugAllergyCreate) SetNillableMannerID(id *int) *DrugAllergyCreate {
	if id != nil {
		dac = dac.SetMannerID(*id)
	}
	return dac
}

// SetManner sets the manner edge to Manner.
func (dac *DrugAllergyCreate) SetManner(m *Manner) *DrugAllergyCreate {
	return dac.SetMannerID(m.ID)
}

// Mutation returns the DrugAllergyMutation object of the builder.
func (dac *DrugAllergyCreate) Mutation() *DrugAllergyMutation {
	return dac.mutation
}

// Save creates the DrugAllergy in the database.
func (dac *DrugAllergyCreate) Save(ctx context.Context) (*DrugAllergy, error) {
	var (
		err  error
		node *DrugAllergy
	)
	if len(dac.hooks) == 0 {
		node, err = dac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DrugAllergyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dac.mutation = mutation
			node, err = dac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dac.hooks) - 1; i >= 0; i-- {
			mut = dac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dac *DrugAllergyCreate) SaveX(ctx context.Context) *DrugAllergy {
	v, err := dac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dac *DrugAllergyCreate) sqlSave(ctx context.Context) (*DrugAllergy, error) {
	da, _spec := dac.createSpec()
	if err := sqlgraph.CreateNode(ctx, dac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	da.ID = int(id)
	return da, nil
}

func (dac *DrugAllergyCreate) createSpec() (*DrugAllergy, *sqlgraph.CreateSpec) {
	var (
		da    = &DrugAllergy{config: dac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: drugallergy.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: drugallergy.FieldID,
			},
		}
	)
	if nodes := dac.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.DoctorTable,
			Columns: []string{drugallergy.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dac.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.PatientTable,
			Columns: []string{drugallergy.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dac.mutation.MedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MedicineTable,
			Columns: []string{drugallergy.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dac.mutation.MannerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MannerTable,
			Columns: []string{drugallergy.MannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return da, _spec
}
