// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/mmildd_s/app/ent/doctor"
	"github.com/mmildd_s/app/ent/drugallergy"
	"github.com/mmildd_s/app/ent/manner"
	"github.com/mmildd_s/app/ent/medicine"
	"github.com/mmildd_s/app/ent/patient"
	"github.com/mmildd_s/app/ent/predicate"
)

// DrugAllergyUpdate is the builder for updating DrugAllergy entities.
type DrugAllergyUpdate struct {
	config
	hooks      []Hook
	mutation   *DrugAllergyMutation
	predicates []predicate.DrugAllergy
}

// Where adds a new predicate for the builder.
func (dau *DrugAllergyUpdate) Where(ps ...predicate.DrugAllergy) *DrugAllergyUpdate {
	dau.predicates = append(dau.predicates, ps...)
	return dau
}

// SetDoctorID sets the doctor edge to Doctor by id.
func (dau *DrugAllergyUpdate) SetDoctorID(id int) *DrugAllergyUpdate {
	dau.mutation.SetDoctorID(id)
	return dau
}

// SetNillableDoctorID sets the doctor edge to Doctor by id if the given value is not nil.
func (dau *DrugAllergyUpdate) SetNillableDoctorID(id *int) *DrugAllergyUpdate {
	if id != nil {
		dau = dau.SetDoctorID(*id)
	}
	return dau
}

// SetDoctor sets the doctor edge to Doctor.
func (dau *DrugAllergyUpdate) SetDoctor(d *Doctor) *DrugAllergyUpdate {
	return dau.SetDoctorID(d.ID)
}

// SetPatientID sets the patient edge to Patient by id.
func (dau *DrugAllergyUpdate) SetPatientID(id int) *DrugAllergyUpdate {
	dau.mutation.SetPatientID(id)
	return dau
}

// SetNillablePatientID sets the patient edge to Patient by id if the given value is not nil.
func (dau *DrugAllergyUpdate) SetNillablePatientID(id *int) *DrugAllergyUpdate {
	if id != nil {
		dau = dau.SetPatientID(*id)
	}
	return dau
}

// SetPatient sets the patient edge to Patient.
func (dau *DrugAllergyUpdate) SetPatient(p *Patient) *DrugAllergyUpdate {
	return dau.SetPatientID(p.ID)
}

// SetMedicineID sets the medicine edge to Medicine by id.
func (dau *DrugAllergyUpdate) SetMedicineID(id int) *DrugAllergyUpdate {
	dau.mutation.SetMedicineID(id)
	return dau
}

// SetNillableMedicineID sets the medicine edge to Medicine by id if the given value is not nil.
func (dau *DrugAllergyUpdate) SetNillableMedicineID(id *int) *DrugAllergyUpdate {
	if id != nil {
		dau = dau.SetMedicineID(*id)
	}
	return dau
}

// SetMedicine sets the medicine edge to Medicine.
func (dau *DrugAllergyUpdate) SetMedicine(m *Medicine) *DrugAllergyUpdate {
	return dau.SetMedicineID(m.ID)
}

// SetMannerID sets the manner edge to Manner by id.
func (dau *DrugAllergyUpdate) SetMannerID(id int) *DrugAllergyUpdate {
	dau.mutation.SetMannerID(id)
	return dau
}

// SetNillableMannerID sets the manner edge to Manner by id if the given value is not nil.
func (dau *DrugAllergyUpdate) SetNillableMannerID(id *int) *DrugAllergyUpdate {
	if id != nil {
		dau = dau.SetMannerID(*id)
	}
	return dau
}

// SetManner sets the manner edge to Manner.
func (dau *DrugAllergyUpdate) SetManner(m *Manner) *DrugAllergyUpdate {
	return dau.SetMannerID(m.ID)
}

// Mutation returns the DrugAllergyMutation object of the builder.
func (dau *DrugAllergyUpdate) Mutation() *DrugAllergyMutation {
	return dau.mutation
}

// ClearDoctor clears the doctor edge to Doctor.
func (dau *DrugAllergyUpdate) ClearDoctor() *DrugAllergyUpdate {
	dau.mutation.ClearDoctor()
	return dau
}

// ClearPatient clears the patient edge to Patient.
func (dau *DrugAllergyUpdate) ClearPatient() *DrugAllergyUpdate {
	dau.mutation.ClearPatient()
	return dau
}

// ClearMedicine clears the medicine edge to Medicine.
func (dau *DrugAllergyUpdate) ClearMedicine() *DrugAllergyUpdate {
	dau.mutation.ClearMedicine()
	return dau
}

// ClearManner clears the manner edge to Manner.
func (dau *DrugAllergyUpdate) ClearManner() *DrugAllergyUpdate {
	dau.mutation.ClearManner()
	return dau
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (dau *DrugAllergyUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(dau.hooks) == 0 {
		affected, err = dau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DrugAllergyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dau.mutation = mutation
			affected, err = dau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dau.hooks) - 1; i >= 0; i-- {
			mut = dau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (dau *DrugAllergyUpdate) SaveX(ctx context.Context) int {
	affected, err := dau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dau *DrugAllergyUpdate) Exec(ctx context.Context) error {
	_, err := dau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dau *DrugAllergyUpdate) ExecX(ctx context.Context) {
	if err := dau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dau *DrugAllergyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   drugallergy.Table,
			Columns: drugallergy.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: drugallergy.FieldID,
			},
		},
	}
	if ps := dau.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if dau.mutation.DoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.DoctorTable,
			Columns: []string{drugallergy.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dau.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.DoctorTable,
			Columns: []string{drugallergy.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dau.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.PatientTable,
			Columns: []string{drugallergy.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dau.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.PatientTable,
			Columns: []string{drugallergy.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dau.mutation.MedicineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MedicineTable,
			Columns: []string{drugallergy.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dau.mutation.MedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MedicineTable,
			Columns: []string{drugallergy.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dau.mutation.MannerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MannerTable,
			Columns: []string{drugallergy.MannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manner.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dau.mutation.MannerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MannerTable,
			Columns: []string{drugallergy.MannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drugallergy.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// DrugAllergyUpdateOne is the builder for updating a single DrugAllergy entity.
type DrugAllergyUpdateOne struct {
	config
	hooks    []Hook
	mutation *DrugAllergyMutation
}

// SetDoctorID sets the doctor edge to Doctor by id.
func (dauo *DrugAllergyUpdateOne) SetDoctorID(id int) *DrugAllergyUpdateOne {
	dauo.mutation.SetDoctorID(id)
	return dauo
}

// SetNillableDoctorID sets the doctor edge to Doctor by id if the given value is not nil.
func (dauo *DrugAllergyUpdateOne) SetNillableDoctorID(id *int) *DrugAllergyUpdateOne {
	if id != nil {
		dauo = dauo.SetDoctorID(*id)
	}
	return dauo
}

// SetDoctor sets the doctor edge to Doctor.
func (dauo *DrugAllergyUpdateOne) SetDoctor(d *Doctor) *DrugAllergyUpdateOne {
	return dauo.SetDoctorID(d.ID)
}

// SetPatientID sets the patient edge to Patient by id.
func (dauo *DrugAllergyUpdateOne) SetPatientID(id int) *DrugAllergyUpdateOne {
	dauo.mutation.SetPatientID(id)
	return dauo
}

// SetNillablePatientID sets the patient edge to Patient by id if the given value is not nil.
func (dauo *DrugAllergyUpdateOne) SetNillablePatientID(id *int) *DrugAllergyUpdateOne {
	if id != nil {
		dauo = dauo.SetPatientID(*id)
	}
	return dauo
}

// SetPatient sets the patient edge to Patient.
func (dauo *DrugAllergyUpdateOne) SetPatient(p *Patient) *DrugAllergyUpdateOne {
	return dauo.SetPatientID(p.ID)
}

// SetMedicineID sets the medicine edge to Medicine by id.
func (dauo *DrugAllergyUpdateOne) SetMedicineID(id int) *DrugAllergyUpdateOne {
	dauo.mutation.SetMedicineID(id)
	return dauo
}

// SetNillableMedicineID sets the medicine edge to Medicine by id if the given value is not nil.
func (dauo *DrugAllergyUpdateOne) SetNillableMedicineID(id *int) *DrugAllergyUpdateOne {
	if id != nil {
		dauo = dauo.SetMedicineID(*id)
	}
	return dauo
}

// SetMedicine sets the medicine edge to Medicine.
func (dauo *DrugAllergyUpdateOne) SetMedicine(m *Medicine) *DrugAllergyUpdateOne {
	return dauo.SetMedicineID(m.ID)
}

// SetMannerID sets the manner edge to Manner by id.
func (dauo *DrugAllergyUpdateOne) SetMannerID(id int) *DrugAllergyUpdateOne {
	dauo.mutation.SetMannerID(id)
	return dauo
}

// SetNillableMannerID sets the manner edge to Manner by id if the given value is not nil.
func (dauo *DrugAllergyUpdateOne) SetNillableMannerID(id *int) *DrugAllergyUpdateOne {
	if id != nil {
		dauo = dauo.SetMannerID(*id)
	}
	return dauo
}

// SetManner sets the manner edge to Manner.
func (dauo *DrugAllergyUpdateOne) SetManner(m *Manner) *DrugAllergyUpdateOne {
	return dauo.SetMannerID(m.ID)
}

// Mutation returns the DrugAllergyMutation object of the builder.
func (dauo *DrugAllergyUpdateOne) Mutation() *DrugAllergyMutation {
	return dauo.mutation
}

// ClearDoctor clears the doctor edge to Doctor.
func (dauo *DrugAllergyUpdateOne) ClearDoctor() *DrugAllergyUpdateOne {
	dauo.mutation.ClearDoctor()
	return dauo
}

// ClearPatient clears the patient edge to Patient.
func (dauo *DrugAllergyUpdateOne) ClearPatient() *DrugAllergyUpdateOne {
	dauo.mutation.ClearPatient()
	return dauo
}

// ClearMedicine clears the medicine edge to Medicine.
func (dauo *DrugAllergyUpdateOne) ClearMedicine() *DrugAllergyUpdateOne {
	dauo.mutation.ClearMedicine()
	return dauo
}

// ClearManner clears the manner edge to Manner.
func (dauo *DrugAllergyUpdateOne) ClearManner() *DrugAllergyUpdateOne {
	dauo.mutation.ClearManner()
	return dauo
}

// Save executes the query and returns the updated entity.
func (dauo *DrugAllergyUpdateOne) Save(ctx context.Context) (*DrugAllergy, error) {

	var (
		err  error
		node *DrugAllergy
	)
	if len(dauo.hooks) == 0 {
		node, err = dauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DrugAllergyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dauo.mutation = mutation
			node, err = dauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dauo.hooks) - 1; i >= 0; i-- {
			mut = dauo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dauo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (dauo *DrugAllergyUpdateOne) SaveX(ctx context.Context) *DrugAllergy {
	da, err := dauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return da
}

// Exec executes the query on the entity.
func (dauo *DrugAllergyUpdateOne) Exec(ctx context.Context) error {
	_, err := dauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dauo *DrugAllergyUpdateOne) ExecX(ctx context.Context) {
	if err := dauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dauo *DrugAllergyUpdateOne) sqlSave(ctx context.Context) (da *DrugAllergy, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   drugallergy.Table,
			Columns: drugallergy.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: drugallergy.FieldID,
			},
		},
	}
	id, ok := dauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing DrugAllergy.ID for update")}
	}
	_spec.Node.ID.Value = id
	if dauo.mutation.DoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.DoctorTable,
			Columns: []string{drugallergy.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dauo.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.DoctorTable,
			Columns: []string{drugallergy.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dauo.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.PatientTable,
			Columns: []string{drugallergy.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dauo.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.PatientTable,
			Columns: []string{drugallergy.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dauo.mutation.MedicineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MedicineTable,
			Columns: []string{drugallergy.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dauo.mutation.MedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MedicineTable,
			Columns: []string{drugallergy.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dauo.mutation.MannerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MannerTable,
			Columns: []string{drugallergy.MannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manner.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dauo.mutation.MannerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugallergy.MannerTable,
			Columns: []string{drugallergy.MannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	da = &DrugAllergy{config: dauo.config}
	_spec.Assign = da.assignValues
	_spec.ScanValues = da.scanValues()
	if err = sqlgraph.UpdateNode(ctx, dauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drugallergy.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return da, nil
}
