// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/mmildd_s/app/ent/manner"
)

// Manner is the model entity for the Manner schema.
type Manner struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MannerName holds the value of the "Manner_Name" field.
	MannerName string `json:"Manner_Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MannerQuery when eager-loading is set.
	Edges MannerEdges `json:"edges"`
}

// MannerEdges holds the relations/edges for other nodes in the graph.
type MannerEdges struct {
	// MannerDrugAllergy holds the value of the Manner_DrugAllergy edge.
	MannerDrugAllergy []*DrugAllergy
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MannerDrugAllergyOrErr returns the MannerDrugAllergy value or an error if the edge
// was not loaded in eager-loading.
func (e MannerEdges) MannerDrugAllergyOrErr() ([]*DrugAllergy, error) {
	if e.loadedTypes[0] {
		return e.MannerDrugAllergy, nil
	}
	return nil, &NotLoadedError{edge: "Manner_DrugAllergy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Manner) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Manner_Name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Manner fields.
func (m *Manner) assignValues(values ...interface{}) error {
	if m, n := len(values), len(manner.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	m.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Manner_Name", values[0])
	} else if value.Valid {
		m.MannerName = value.String
	}
	return nil
}

// QueryMannerDrugAllergy queries the Manner_DrugAllergy edge of the Manner.
func (m *Manner) QueryMannerDrugAllergy() *DrugAllergyQuery {
	return (&MannerClient{config: m.config}).QueryMannerDrugAllergy(m)
}

// Update returns a builder for updating this Manner.
// Note that, you need to call Manner.Unwrap() before calling this method, if this Manner
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Manner) Update() *MannerUpdateOne {
	return (&MannerClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (m *Manner) Unwrap() *Manner {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Manner is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Manner) String() string {
	var builder strings.Builder
	builder.WriteString("Manner(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", Manner_Name=")
	builder.WriteString(m.MannerName)
	builder.WriteByte(')')
	return builder.String()
}

// Manners is a parsable slice of Manner.
type Manners []*Manner

func (m Manners) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
