// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/mmildd_s/app/ent/drugallergy"
	"github.com/mmildd_s/app/ent/medicine"
	"github.com/mmildd_s/app/ent/predicate"
)

// MedicineUpdate is the builder for updating Medicine entities.
type MedicineUpdate struct {
	config
	hooks      []Hook
	mutation   *MedicineMutation
	predicates []predicate.Medicine
}

// Where adds a new predicate for the builder.
func (mu *MedicineUpdate) Where(ps ...predicate.Medicine) *MedicineUpdate {
	mu.predicates = append(mu.predicates, ps...)
	return mu
}

// SetMedicineName sets the Medicine_Name field.
func (mu *MedicineUpdate) SetMedicineName(s string) *MedicineUpdate {
	mu.mutation.SetMedicineName(s)
	return mu
}

// AddMedicineDrugAllergyIDs adds the Medicine_DrugAllergy edge to DrugAllergy by ids.
func (mu *MedicineUpdate) AddMedicineDrugAllergyIDs(ids ...int) *MedicineUpdate {
	mu.mutation.AddMedicineDrugAllergyIDs(ids...)
	return mu
}

// AddMedicineDrugAllergy adds the Medicine_DrugAllergy edges to DrugAllergy.
func (mu *MedicineUpdate) AddMedicineDrugAllergy(d ...*DrugAllergy) *MedicineUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return mu.AddMedicineDrugAllergyIDs(ids...)
}

// Mutation returns the MedicineMutation object of the builder.
func (mu *MedicineUpdate) Mutation() *MedicineMutation {
	return mu.mutation
}

// RemoveMedicineDrugAllergyIDs removes the Medicine_DrugAllergy edge to DrugAllergy by ids.
func (mu *MedicineUpdate) RemoveMedicineDrugAllergyIDs(ids ...int) *MedicineUpdate {
	mu.mutation.RemoveMedicineDrugAllergyIDs(ids...)
	return mu
}

// RemoveMedicineDrugAllergy removes Medicine_DrugAllergy edges to DrugAllergy.
func (mu *MedicineUpdate) RemoveMedicineDrugAllergy(d ...*DrugAllergy) *MedicineUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return mu.RemoveMedicineDrugAllergyIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (mu *MedicineUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := mu.mutation.MedicineName(); ok {
		if err := medicine.MedicineNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Medicine_Name", err: fmt.Errorf("ent: validator failed for field \"Medicine_Name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicineMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MedicineUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MedicineUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MedicineUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MedicineUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   medicine.Table,
			Columns: medicine.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicine.FieldID,
			},
		},
	}
	if ps := mu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.MedicineName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicine.FieldMedicineName,
		})
	}
	if nodes := mu.mutation.RemovedMedicineDrugAllergyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicine.MedicineDrugAllergyTable,
			Columns: []string{medicine.MedicineDrugAllergyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drugallergy.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MedicineDrugAllergyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicine.MedicineDrugAllergyTable,
			Columns: []string{medicine.MedicineDrugAllergyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drugallergy.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{medicine.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// MedicineUpdateOne is the builder for updating a single Medicine entity.
type MedicineUpdateOne struct {
	config
	hooks    []Hook
	mutation *MedicineMutation
}

// SetMedicineName sets the Medicine_Name field.
func (muo *MedicineUpdateOne) SetMedicineName(s string) *MedicineUpdateOne {
	muo.mutation.SetMedicineName(s)
	return muo
}

// AddMedicineDrugAllergyIDs adds the Medicine_DrugAllergy edge to DrugAllergy by ids.
func (muo *MedicineUpdateOne) AddMedicineDrugAllergyIDs(ids ...int) *MedicineUpdateOne {
	muo.mutation.AddMedicineDrugAllergyIDs(ids...)
	return muo
}

// AddMedicineDrugAllergy adds the Medicine_DrugAllergy edges to DrugAllergy.
func (muo *MedicineUpdateOne) AddMedicineDrugAllergy(d ...*DrugAllergy) *MedicineUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return muo.AddMedicineDrugAllergyIDs(ids...)
}

// Mutation returns the MedicineMutation object of the builder.
func (muo *MedicineUpdateOne) Mutation() *MedicineMutation {
	return muo.mutation
}

// RemoveMedicineDrugAllergyIDs removes the Medicine_DrugAllergy edge to DrugAllergy by ids.
func (muo *MedicineUpdateOne) RemoveMedicineDrugAllergyIDs(ids ...int) *MedicineUpdateOne {
	muo.mutation.RemoveMedicineDrugAllergyIDs(ids...)
	return muo
}

// RemoveMedicineDrugAllergy removes Medicine_DrugAllergy edges to DrugAllergy.
func (muo *MedicineUpdateOne) RemoveMedicineDrugAllergy(d ...*DrugAllergy) *MedicineUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return muo.RemoveMedicineDrugAllergyIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (muo *MedicineUpdateOne) Save(ctx context.Context) (*Medicine, error) {
	if v, ok := muo.mutation.MedicineName(); ok {
		if err := medicine.MedicineNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Medicine_Name", err: fmt.Errorf("ent: validator failed for field \"Medicine_Name\": %w", err)}
		}
	}

	var (
		err  error
		node *Medicine
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicineMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MedicineUpdateOne) SaveX(ctx context.Context) *Medicine {
	m, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return m
}

// Exec executes the query on the entity.
func (muo *MedicineUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MedicineUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MedicineUpdateOne) sqlSave(ctx context.Context) (m *Medicine, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   medicine.Table,
			Columns: medicine.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicine.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Medicine.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := muo.mutation.MedicineName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicine.FieldMedicineName,
		})
	}
	if nodes := muo.mutation.RemovedMedicineDrugAllergyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicine.MedicineDrugAllergyTable,
			Columns: []string{medicine.MedicineDrugAllergyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drugallergy.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MedicineDrugAllergyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicine.MedicineDrugAllergyTable,
			Columns: []string{medicine.MedicineDrugAllergyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drugallergy.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	m = &Medicine{config: muo.config}
	_spec.Assign = m.assignValues
	_spec.ScanValues = m.scanValues()
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{medicine.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return m, nil
}
