/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrugAllergy,
    EntDrugAllergyFromJSON,
    EntDrugAllergyFromJSONTyped,
    EntDrugAllergyToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientEdges
 */
export interface EntPatientEdges {
    /**
     * PatientDrugAllergy holds the value of the Patient_DrugAllergy edge.
     * @type {Array<EntDrugAllergy>}
     * @memberof EntPatientEdges
     */
    patientDrugAllergy?: Array<EntDrugAllergy>;
}

export function EntPatientEdgesFromJSON(json: any): EntPatientEdges {
    return EntPatientEdgesFromJSONTyped(json, false);
}

export function EntPatientEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientDrugAllergy': !exists(json, 'patientDrugAllergy') ? undefined : ((json['patientDrugAllergy'] as Array<any>).map(EntDrugAllergyFromJSON)),
    };
}

export function EntPatientEdgesToJSON(value?: EntPatientEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientDrugAllergy': value.patientDrugAllergy === undefined ? undefined : ((value.patientDrugAllergy as Array<any>).map(EntDrugAllergyToJSON)),
    };
}


