// Code generated by entc, DO NOT EDIT.

package manner

const (
	// Label holds the string label denoting the manner type in the database.
	Label = "manner"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMannerName holds the string denoting the manner_name field in the database.
	FieldMannerName = "manner_name"

	// EdgeMannerDrugAllergy holds the string denoting the manner_drugallergy edge name in mutations.
	EdgeMannerDrugAllergy = "Manner_DrugAllergy"

	// Table holds the table name of the manner in the database.
	Table = "manners"
	// MannerDrugAllergyTable is the table the holds the Manner_DrugAllergy relation/edge.
	MannerDrugAllergyTable = "drug_allergies"
	// MannerDrugAllergyInverseTable is the table name for the DrugAllergy entity.
	// It exists in this package in order to avoid circular dependency with the "drugallergy" package.
	MannerDrugAllergyInverseTable = "drug_allergies"
	// MannerDrugAllergyColumn is the table column denoting the Manner_DrugAllergy relation/edge.
	MannerDrugAllergyColumn = "manner_id"
)

// Columns holds all SQL columns for manner fields.
var Columns = []string{
	FieldID,
	FieldMannerName,
}

var (
	// MannerNameValidator is a validator for the "Manner_Name" field. It is called by the builders before save.
	MannerNameValidator func(string) error
)
