// Code generated by entc, DO NOT EDIT.

package manner

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/mmildd_s/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// MannerName applies equality check predicate on the "Manner_Name" field. It's identical to MannerNameEQ.
func MannerName(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMannerName), v))
	})
}

// MannerNameEQ applies the EQ predicate on the "Manner_Name" field.
func MannerNameEQ(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMannerName), v))
	})
}

// MannerNameNEQ applies the NEQ predicate on the "Manner_Name" field.
func MannerNameNEQ(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMannerName), v))
	})
}

// MannerNameIn applies the In predicate on the "Manner_Name" field.
func MannerNameIn(vs ...string) predicate.Manner {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Manner(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMannerName), v...))
	})
}

// MannerNameNotIn applies the NotIn predicate on the "Manner_Name" field.
func MannerNameNotIn(vs ...string) predicate.Manner {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Manner(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMannerName), v...))
	})
}

// MannerNameGT applies the GT predicate on the "Manner_Name" field.
func MannerNameGT(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMannerName), v))
	})
}

// MannerNameGTE applies the GTE predicate on the "Manner_Name" field.
func MannerNameGTE(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMannerName), v))
	})
}

// MannerNameLT applies the LT predicate on the "Manner_Name" field.
func MannerNameLT(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMannerName), v))
	})
}

// MannerNameLTE applies the LTE predicate on the "Manner_Name" field.
func MannerNameLTE(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMannerName), v))
	})
}

// MannerNameContains applies the Contains predicate on the "Manner_Name" field.
func MannerNameContains(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMannerName), v))
	})
}

// MannerNameHasPrefix applies the HasPrefix predicate on the "Manner_Name" field.
func MannerNameHasPrefix(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMannerName), v))
	})
}

// MannerNameHasSuffix applies the HasSuffix predicate on the "Manner_Name" field.
func MannerNameHasSuffix(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMannerName), v))
	})
}

// MannerNameEqualFold applies the EqualFold predicate on the "Manner_Name" field.
func MannerNameEqualFold(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMannerName), v))
	})
}

// MannerNameContainsFold applies the ContainsFold predicate on the "Manner_Name" field.
func MannerNameContainsFold(v string) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMannerName), v))
	})
}

// HasMannerDrugAllergy applies the HasEdge predicate on the "Manner_DrugAllergy" edge.
func HasMannerDrugAllergy() predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MannerDrugAllergyTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MannerDrugAllergyTable, MannerDrugAllergyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMannerDrugAllergyWith applies the HasEdge predicate on the "Manner_DrugAllergy" edge with a given conditions (other predicates).
func HasMannerDrugAllergyWith(preds ...predicate.DrugAllergy) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MannerDrugAllergyInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MannerDrugAllergyTable, MannerDrugAllergyColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Manner) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Manner) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Manner) predicate.Manner {
	return predicate.Manner(func(s *sql.Selector) {
		p(s.Not())
	})
}
